// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAynfTZZxQGt6Wnpgs9bgDxt7VjyTSiUuA',
    appId: '1:280085330347:web:4063a2bfee7feec2663aee',
    messagingSenderId: '280085330347',
    projectId: 'chat-app-a863d',
    authDomain: 'chat-app-a863d.firebaseapp.com',
    storageBucket: 'chat-app-a863d.appspot.com',
    measurementId: 'G-1C22RCW9GW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkzsBwxE3qciRSxcy0Zz_nHLl6j9G-N9A',
    appId: '1:280085330347:android:3eeed9d10cba423e663aee',
    messagingSenderId: '280085330347',
    projectId: 'chat-app-a863d',
    storageBucket: 'chat-app-a863d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn6UB1gkucKJHeyt6uRBYFcCIpQrLHLuI',
    appId: '1:280085330347:ios:d0c9c7c78b1ac2bb663aee',
    messagingSenderId: '280085330347',
    projectId: 'chat-app-a863d',
    storageBucket: 'chat-app-a863d.appspot.com',
    iosClientId: '280085330347-j0k7rert7vnjc5g0n4upt4f5f4d62smv.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn6UB1gkucKJHeyt6uRBYFcCIpQrLHLuI',
    appId: '1:280085330347:ios:d0c9c7c78b1ac2bb663aee',
    messagingSenderId: '280085330347',
    projectId: 'chat-app-a863d',
    storageBucket: 'chat-app-a863d.appspot.com',
    iosClientId: '280085330347-j0k7rert7vnjc5g0n4upt4f5f4d62smv.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
